### ISSUE TITLE
Include image explaining anatomical directions

### ISSUE THREAD

**Issue by niksirbi** [afids/afids-macaca#2]
The instructions for placing the fiducials are quite helpful, but assume that one has good knowledge of the anatomical terminology (superior, inferior etc.). While most annotators will be familiar with the terms, it might still be useful to include a graphic indicating the main directions and their names

**Comment by greydongilmore** [comment]
![image](https://user-images.githubusercontent.com/26314366/78950245-2146db00-7a9c-11ea-980b-e6cf93e05240.png)

**Comment by ggupta23** [comment]
![Snip20200409_55](https://user-images.githubusercontent.com/30180157/78955874-96bba700-7aae-11ea-956c-0b7f5f8e95a5.png)

**Comment by niksirbi** [comment]
Thanks @greydongilmore, that's exactly what I meant! There is a typo on the axial image. The lower label should be 'posterior', not 'inferior'

**Comment by niksirbi** [comment]
@ggupta23 that will also be useful, but I was first taken aback because I thought you were labeling the sides of each slice (which obviously don't match). It took me a few seconds to realize you were referring to the direction of the sliders (despite your clever trick to use the slider colors). Maybe you can come up with an additional trick to ensure this confusion never arises?

**Comment by greydongilmore** [comment]
added these images for both human and nhp in commit 4a347d1f2babd29683c322bf42dd8bbad1abde56
